<!DOCTYPE html>
<html lang="en">
<head>

	<meta charset="utf-8" />

	<title></title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

	<link rel="stylesheet" href="libs/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="css/main.css" />
	<link rel="stylesheet" href="css/media.css" />
	<link rel="stylesheet" href="css/fonts.css" />

</head>

<body>
 <!-- Full Page Image Background Carousel Header -->
 <div class="container mgt8">
	  <div class="row">
<!--------------------------------NAV BT-------------------------------->
         <div id="nav-icon" class="col-lg-2 col-lg-offset-1" data-effect="st-effect-1">
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
         </div>
<!---------------------------------LOGO--------------------------------->
         <div class="logo_main col-lg-4 col-lg-offset-1">
				<a href=""><img src="../img/logo.png"></a>
          </div>
<!---------------------------------NAV---------------------------------->
          <div class="navMn col-lg-4 col-lg-offset-1">
            <nav class="collapse navbar-collapse" role="navigation">
                <ul id="menu-primary-navigation-en" class="nav navbar-nav">
                    <li class="menu-home"><a href="" class=" roll"><span data-title="Home">Home</span></a></li>
                    <li class="menu-about"><a href="" class=" roll"><span data-title="About">About</span></a></li>
                    <li class="menu-portfolio"><a href="" class=" roll"><span data-title="Portfolio">Portfolio</span></a></li>
                </ul>
            </nav>
          </div>
      </div>
	</div>
 <header id="myCarousel" class="carousel slide">
		 <!-- Indicators -->
		 <ol class="carousel-indicators">
				 <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
				 <li data-target="#myCarousel" data-slide-to="1"></li>
				 <li data-target="#myCarousel" data-slide-to="2"></li>
		 </ol>

		 <!-- Wrapper for Slides -->
		 <div class="carousel-inner">

				 <div class="item active">
						 <!-- Set the first background image using inline CSS below. -->
						 <div class="fill" style="background-image:url('../img/first_bg.jpg');"></div>
						 <div class="carousel-caption">
								 <h2>First slider</h2>
						 </div>
				 </div>

				 <div class="item">
						 <!-- Set the second background image using inline CSS below. -->
						 <div class="fill" style="background-image:url('../img/second_bg.jpg');"></div>
						 <div class="carousel-caption">
								 <h2>Second slider</h2>
						 </div>
				 </div>

				 <div class="item">
						 <!-- Set the third background image using inline CSS below. -->
						 <div class="fill" style="background-image:url('../img/third_bg.jpg');"></div>
						 <div class="carousel-caption">
								 <h2>Third slider</h2>
						 </div>
				 </div>
		 </div>

		 <!-- Controls -->
		 <a class="left carousel-control" href="#myCarousel" data-slide="prev">
				 <span class="icon-prev"></span>
		 </a>
		 <a class="right carousel-control" href="#myCarousel" data-slide="next">
				 <span class="icon-next"></span>
		 </a>
	</header>

	<content select="">ANOTHER CONTENT</content>

	<footer>
	</footer>

	<script src="libs/jquery/jquery-2.1.4.min.js"></script>
	<script src="libs/bootstrap/js/bootstrap.min.js"></script>
	<script src="js/main.js."></script>
	<script src="js/common.js"></script>

</body>
</html>
